[package]
name = "cadre"
version = "0.1.0"
authors = ["Eric Zhang <ekzhang1@gmail.com>"]
license = "MIT"
description = "Cadre is a simple, self-hosted, high-performance, and strongly consistent remote configuration service."
repository = "https://github.com/modal-labs/cadre"
documentation = "https://docs.rs/cadre"
keywords = ["config", "web", "service", "remote"]
categories = ["development-tools", "web-programming", "config", "database"]
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
axum = "0.5.4"
home = "0.5.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tempfile = "3.3.0"
tokio = { version = "1.18.1", features = ["full"] }
